# Generated by Django 5.2.9 on 2026-01-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_menuitem_options_menuitem_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='type',
            field=models.CharField(choices=[('fast_food', 'Fast Food'), ('fine_dining', 'Fine Dining'), ('cafe', 'Cafe'), ('casual_dining', 'Casual Dining'), ('food_truck', 'Food Truck'), ('buffet', 'Buffet'), ('pop_up', 'Pop Up'), ('delivery_only', 'Delivery Only')], default='casual_dining', max_length=50),
        ),
    ]
